name: Unit tests
on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run test command
        run: npm run test -- --watchAll=false
